---
title: "projectReport.Rmd"
author: "DS 202 Group 9"
date: "5/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

Cereal is one of the most popular choices for breakfast in many places. Many cereals can be very healthy due to their vitamin and mineral content as well as containing fiber, protein and whole grain. On the other hand many can be unhealthy due to high sugar content and lack of healthy ingredients. Our group wanted to create a buyer's guide to help consumers choose the right cereal for their needs. In this report we will be exploring 80 different cereals and comparing them based on nutritional value, rating and quality.


## Questions Raised

Our group came up with the following questions that may impact the choice that an everyday consumer might make when purchasing cereal. 

These questions include:

 1) What is the correlation between nutritional values and rating?
 2) What manufacturers have the most top shelf and bottom shelf cereals?
 3) What are the healthiest and least healthiest cold cereals?
 4) Do people prefer hot or cold cereal based off of the rating?
 5) Who are the “healthiest” and “least healthiest” manufacturers?
 6) What is a healthy cereal for kids based off of nutritional facts?
 7) What is a healthy cereal for adults/elders based off of nutritional facts?
 8) How much of the best/worst cereals can one have before exceeding recommended levels?
 9) Which shelf has the higher average rating?


## Obtaining and Cleaning the Dataset

The cereal information that we are using is from a website called Kaggle. The link to download the .csv file can be found [here](https://www.kaggle.com/crawford/80-cereals). A limiting constraint that this data set possesses is that we do not have any null values. Instead of null values, we have -1s in their place. To work around this, we decided to alter the columns that were needed to answer our questions by only keeping values that were 0 or above. This allowed us to remove the null values without methods such as na.omit() in dplyr functions. Other than that, the data set was clean for the most part.


## Exploratory Analysis and A few questions raised



## Steps for data wrangling and visualization



## Answers to the quesitons raised




## Conclusion






## Contributions

### Alex Son
Place Contributing Paragraph Here

### Madalyn Mueller
1) Do people prefer hot or cold cereal based off of the rating?

To find this, I first made two filtered data sets of cold and hot cereals, and then printed the mean rating for both of these data sets. I realized this was not the best way to compare the ratings, so I decided to do a different approach.

I looked at the highest rated hot cereals, the highest rated cold cereals, and the highest rated cereals overall. I realized that only one of the 10 highest rated cereals was a hot cereal, the rest were cold.

Based on the rating, people prefer cold cereal, although hot cereal still had some high ratings. It is also hard to compare because there are 74 cold cereals and 3 hot cereals.

2) Which manufacturer has the highest average rating?

To find this, I made filtered data sets of all 7 of the manufacturers (American Home Food Products, General Mills, Kelloggs, Nabisco, Post, Quaker Oats, Ralston Purina). Then I printed the average/mean ratings for each filtered data set.

Nabisco is the manufacturer with the highest average rating. This makes sense, because five out of the 10 highest rated cereals are produced by Nabisco. Their cereals include 100% Bran, Cream of Wheat, Shredded Wheat, and Strawberry Fruit Wheats.

### Mike Brown


### Nathan Marquardt
Place Contributing Paragraph Here

### Sydney Thompson
1) What is a healthy cereal for kids based on nutritional facts?

I looked into healthy cereals for kids from ages 4-8 and 9-13 based off of their fiber and sodium intake levels for breakfast only. In doing so, I used nutritional data from a USDA daily intake summary table and made a ratio of the daily values and average cups per serving of cereal to compute the fiber and sodium values for breakfast intake. I found that for kids ages 4-8 should receive 6 or more grams of fiber and 150 grams or less of sodium and kids ages 9-13 should receive 7 or more grams of fiber and 200 grams or less of sodium. As a result, I found that both age groups should consume 100% Bran and/or All-Bran with Extra Fiber cereals if they are looking for a healthy breakfast.

2) What is a healthy cereal for adults/elders based on nutritional facts?

I also looked into healthy cereals for adults, male and female of ages 19-50, as well as elders, male and female of ages 70+. Men of ages 19-50 should consume 9 or more grams of fiber and 200 grams or less of sodium and women of the same age range should consume 6 grams or more of fiber and 200 grams or less of sodium. Males of 70+ should eat 7 grams or more of fiber and 150 grams or less of sodium and females of 70+ should eat 5 grams or more of fiber and 150 grams or less of sodium. As a result, Males 19-50, 70+ and females 70+ should eat 100% Bran and/or All-Bran with Extra Fiber if they're looking to buy a healthy cereal based on fiber and sodium intake. In addition, females of ages 19-50 also should purchase 100% Bran and All-Bran with Extra Fiber as well as a third cereal being Post Natural Raisin Bran. 

3) How much of the healthiest/least healthiest cereal can one have before exceeding recommended levels?

Using the same USDA daily intake summary table for male and female ages 19-50, I made a ratio of daily calories to meals per day to compute the amount of calories a male and female should consume approximately for breakfast and I concluded that men should have roughly 600 calories and females should have 500. After calculating the two I found the calories per serving in cups for the healthiest cereal, All-Bran with Extra Fiber, and the least healthiest cereal, Gold Crisp. With those values I created a simple equation of dividing the male and female calorie intake by the amount of calories per serving and then multiplied that value by the amount of cereal in cups. I found that men can have roughly 6 cups of the healthiest cereal and about 5.28 cups of the least healthiest cereal and for women 5 cups of the healthiest and 4.4 cups of the least healthiest. 

I also contributed as a whole in finding a data set, further researching for information to make our analysis more complex, putting together and presenting slides for our group presentation and writing/creating the final report. 


### Vismay Gehlot
1) What is the healthiest cold cereal?

To figure this out, I used the "cold" filtered data set that Madalyn had previously created. After this, I used the order function to reformat the data set into a list that orders by fiber in descending order and sugars in ascending order. I used these two measurements because we had previously defined that a healthy cereal would be considered one that is high in fiber and low in sugar. From this list, I learned that All-Bran with Extra Fiber is the healthiest cold cereal, as it contains 14 grams of fiber and 0 sugars per serving.


2) What is the least healthiest cereal?

This was similar to my first question, so I only had to change a little bit. This time, I ordered the cold cereal data set by fiber in ascending and sugar in descending instead of vice-versa. This allowed me to see which cereals were highest in sugar and lowest in fiber, making them unhealthy by our standards. From this list, I learned that Golden Crisp is the least healthiest cold cereal, as it contains no fiber and 15 grams of sugar per serving.